/**
 * Playground seam — the REAL verifier, browser-side (owner commission 2026-07-13).
 *
 * This module is the entire bridge between the /playground page and the shipped
 * engine: it composes exactly the two calls the CLI's TRUTH leg composes
 * (`acpFeedToClaims` → `runListingsVerification`, see lib/packs/listings/cli.ts
 * runCheck) against the committed synthetic SOR catalog. Nothing is re-implemented
 * and nothing is mocked: the golden-equality test in
 * evals/packs/playground-golden.test.ts proves this seam, fed the committed
 * drifted sample feed, reproduces fixtures/synthetic-restaurant/expected-report.acp.json
 * byte-for-byte — the same equality the page claims on its face.
 *
 * Browser safety: every transitive import in this closure is pure TypeScript —
 * no node:fs, no network. The same test walks the import graph and asserts it.
 *
 * Honesty by construction: the reference is an illustrative catalog, so every
 * report this seam produces carries `matchingMode: "synthetic-controlled"` — a
 * pasted feed is genuinely verified, live, but always against the committed
 * illustrative merchant records.
 *
 * Client-bundle de-jargon (reconcile 2026-07-14): this CLIENT module imports the
 * JARGON-STRIPPED browser PROJECTIONS of the catalog + sample feed (generated by
 * scripts-ts/generate-browser-fixtures.mts from the canonical fixtures), so lab
 * labels never ship in the JS chunks. The projections copy every engine-read /
 * claim field verbatim, so the report stays byte-identical to the golden (proven
 * by evals/packs/playground-golden.test.ts + browser-fixtures.test.ts).
 */
import type { AcpFeed } from "@/lib/packs/listings/acp-feed";
import { acpFeedToClaims } from "@/lib/packs/listings/adapters";
import { runListingsVerification } from "@/lib/packs/listings/run";
import type { SyntheticCatalog } from "@/lib/packs/listings/types";
import type { VerifierReport } from "@/lib/verifier-core/report";
import sorCatalogJson from "@/fixtures/synthetic-restaurant/browser/sor.catalog.web.json";
import sampleFeedJson from "@/fixtures/synthetic-restaurant/browser/acp-feed.web.json";

/**
 * The browser projections drop the top-level provenance metadata (simulated /
 * generator / merchantName) so no lab-label ships in the JS bundle — but the
 * TYPES require those fields, and they are all still TRUE of this data. They are
 * reconstructed here with honest values instead of casting through `unknown`
 * (phase-F batch finding #10): the engine never reads them (the golden-equality
 * suite proves the computed report stays byte-identical either way).
 */

/** The committed synthetic merchant records every playground run is checked against. */
export const SOR_CATALOG: SyntheticCatalog = {
  simulated: true,
  generator: { name: "browser projection of the committed fixture", seed: 0, version: "web" },
  merchantName: "Illustrative merchant",
  ...(sorCatalogJson as Pick<SyntheticCatalog, "currency" | "asOf" | "items">),
};

/** The committed drifted sample feed (the demo's feed) — the "load sample" source. */
export const SAMPLE_FEED: AcpFeed = {
  simulated: true,
  ...(sampleFeedJson as Pick<AcpFeed, "spec" | "items">),
};

/** Pretty-printed sample feed text for the paste box. */
export function sampleFeedText(): string {
  return JSON.stringify(SAMPLE_FEED, null, 2);
}

/**
 * Display-layer copy cleanup for rendered finding text (matches /report + /demo).
 * The illustrative feed's ghost item carries a lab-label inside its own title —
 * a genuine claim value the frozen golden quotes verbatim — so rendered receipts
 * reword it to the site's plain example voice. Serialization (the golden test) is
 * unaffected; this only touches what a reader sees.
 */
export function cleanFinding(s: string): string {
  return s.replace(/\bsimulated\b/gi, "example").replace(/\bsynthetic\b/gi, "illustrative");
}

export type ParseResult =
  | { readonly ok: true; readonly feed: AcpFeed }
  | { readonly ok: false; readonly error: string };

/**
 * Parse pasted text as an ACP feed — honest, specific failures; never a fake
 * verdict. Mirrors the CLI's shape check (cli.ts checks `Array.isArray(items)`
 * on the SOR; the feed-side equivalent here).
 */
export function parseAcpFeedText(text: string): ParseResult {
  if (!text.trim()) {
    return { ok: false, error: "The paste box is empty — paste an ACP feed JSON document first." };
  }
  let raw: unknown;
  try {
    raw = JSON.parse(text);
  } catch (e) {
    return {
      ok: false,
      error: `Not valid JSON: ${e instanceof Error ? e.message : String(e)}`,
    };
  }
  if (typeof raw !== "object" || raw === null || Array.isArray(raw)) {
    return { ok: false, error: "Expected a JSON object with an `items` array — got a non-object." };
  }
  const items = (raw as { items?: unknown }).items;
  if (!Array.isArray(items)) {
    return {
      ok: false,
      error:
        "This does not look like an ACP feed: the top-level `items` array is missing. See the sample feed for the expected shape.",
    };
  }
  // batch-F P2 fix: a null / non-object / id-less row would throw inside the
  // engine instead of reaching the honest error path — validate row shape
  // first. Wrong or missing FIELD VALUES stay verifiable (they surface as
  // findings); only rows the adapter cannot even read are rejected here.
  for (let i = 0; i < items.length; i++) {
    const row = items[i];
    if (typeof row !== "object" || row === null || Array.isArray(row)) {
      return {
        ok: false,
        error: `items[${i}] is not an object — every feed row must be a JSON object. See the sample feed for the expected shape.`,
      };
    }
    if (typeof (row as { item_id?: unknown }).item_id !== "string") {
      return {
        ok: false,
        error: `items[${i}] has no string \`item_id\` — every feed row needs one so its findings can name the row they belong to.`,
      };
    }
  }
  return { ok: true, feed: raw as AcpFeed };
}

/**
 * Run the real verification — the exact CLI composition, in the browser.
 * Deterministic: same feed in, same report out.
 */
export function verifyAcpFeed(feed: AcpFeed): VerifierReport {
  return runListingsVerification(acpFeedToClaims(feed), SOR_CATALOG);
}
