#!/usr/bin/env bash
# Codex seat smoke probe — run this OUTSIDE the agent sandbox.
#
# WHY THIS SCRIPT EXISTS. Session 40 archived the startup contract from ~312,000
# tokens (156% of a 200k context window) down to ~31,000. That measurement is
# solid and pinned by a test. What it does NOT establish is that the Codex seat
# actually answers — the obstacle being gone is a different claim from the gate
# working, and the record keeps them apart.
#
# The probe could not run from the agent's seat: the sandbox blocks
# chatgpt.com (verified with a control — permitted hosts return real status
# codes, Codex's return 000) and `codex doctor` independently reports
# "ChatGPT base URL https://chatgpt.com/backend-api/ connect failed (required)".
#
# So this runs on the owner's shell, and writes its own record. One command,
# no follow-up needed:
#
#     ./scripts/codex-probe.sh
#
# It records the RAW result either way. A failed probe is a real finding —
# the standing rule is to surface the raw error, never to silently retry,
# downgrade, or switch accounts (that is an owner action).

set -uo pipefail
cd "$(dirname "$0")/.."

STAMP="$(date -u +%Y-%m-%dT%H-%M-%SZ)"
OUT="docs/reviews/codex-seat-probe-${STAMP}.md"
mkdir -p docs/reviews

echo "Probing the Codex seat (config: $(grep -E '^model' ~/.codex/config.toml 2>/dev/null | head -1))..."
echo

# `< /dev/null` is load-bearing. Invoked from a shell whose stdin stays open
# (a `!` command inside an agent session, a CI step, a pipe), `codex exec`
# prints "Reading additional input from stdin..." and waits forever for input
# that never arrives. It looks identical to a slow probe and it never finishes.
# Observed 2026-07-31 when the owner ran the model-override probe by hand.
#
# Pinning the model here rather than trusting config.toml, for the reason this
# script exists: the 16:47Z probe found the seat answering GPT-5.4 while
# `~/.codex/config.toml` declared `gpt-5.6-sol`. Config states intent; only the
# reply states fact. Owner directive 2026-07-31: use only gpt-5.6-sol.
RAW="$(codex exec -c model='"gpt-5.6-sol"' --sandbox read-only \
  'Reply with exactly: SEAT_OK <your model name>. Nothing else.' < /dev/null 2>&1)"
CODE=$?

if printf '%s' "$RAW" | grep -q "SEAT_OK"; then
  # Answering is not enough. The 16:47Z probe returned SEAT_OK from GPT-5.4
  # while config.toml declared gpt-5.6-sol -- so a bare SEAT_OK check would
  # have reported success on the very mismatch this script exists to find.
  if printf '%s' "$RAW" | grep -qiE "5\.6"; then
    VERDICT="SEAT_OK — the seat answered, and it is 5.6"
    MEANING="The Codex seat is reachable, responding, and reports a 5.6 model,
matching the owner's 2026-07-31 directive (\"use only gpt 5.6 sol\") and the
\`model\` pin in this script. The claim \"the cross-model gate is runnable
again\" is **demonstrated**, not inferred."
  else
    VERDICT="SEAT ANSWERED, BUT NOT ON 5.6 — model mismatch"
    MEANING="The seat is reachable, so the gate can run. **But it did not answer
as a 5.6 model**, despite this script pinning \`-c model='\"gpt-5.6-sol\"'\`.

That means the override is not taking effect — most likely the account does not
serve \`gpt-5.6-sol\`, so \`~/.codex/config.toml\`'s declaration is aspirational
rather than descriptive. **This is seat provisioning: an owner action.** Do not
silently retry, downgrade, or switch accounts.

Until it is resolved, any review recorded as running on \`gpt-5.6-sol\` should
be treated as **UNVERIFIED** unless its own probe named the model."
  fi
else
  VERDICT="NO ANSWER — exit ${CODE}"
  MEANING="The seat did NOT answer. This is a real finding, not a retry prompt.
Per the standing rule: surface the raw output, never silently retry, downgrade,
or switch accounts — seat and credential management is an owner action."
fi

cat > "$OUT" <<EOF
# Codex seat smoke probe — ${STAMP}

**Verdict: ${VERDICT}**

${MEANING}

## Why this probe was owed

Session 40 archived the \`AGENTS.md\`:7 startup contract after three cross-model
gate runs died on it (sessions 34, 36, 38). Measured in the unit that actually
broke:

| | before | after |
|---|---:|---:|
| startup read list | ~312,000 tokens | ~31,000 tokens |
| share of a 200k context window | **156%** | **15%** |

A reviewer ordered to read that contract before doing anything could not fit it
in a context window at all — the runs were not slow, they were arithmetically
impossible. That is pinned by \`evals/packs/startup-contract-budget.test.ts\`.

But removing the obstacle is not the same as the seat working. This probe is the
half the agent's seat could not reach: the sandbox blocks \`chatgpt.com\`.

## Raw output (verbatim, never edited)

\`\`\`
${RAW}
\`\`\`

Exit code: \`${CODE}\`

---
Generated by \`scripts/codex-probe.sh\`.
EOF

echo "$RAW"
echo
echo "──────────────────────────────────────────"
echo "  ${VERDICT}"
echo "  record written: ${OUT}"
echo "──────────────────────────────────────────"
